### ISSUE TITLE
Add content to explain Partenariats et commandites

### ISSUE THREAD

**Issue by vigliensoni** [sessions-marteau/sessions-marteau-2.github.io#12]
We need content for this page: https://sessionsmarteau.com/sessions-marteau-2.github.io/partenariats/

**Comment by SessionsHugues** [comment]
I will try to come up with something short, sharp and meaningful, all right.

**Comment by vigliensoni** [comment]
@SessionsHugues great!

**Comment by vigliensoni** [comment]
You can send the text over or you can edit it directly [in this file](https://github.com/sessions-marteau/sessions-marteau-2.github.io/blob/master/_posts/2018-08-23-partenariats.md). 

To edit it directly:

1. Click on the pencil icon and change the text (leave the metadata between `---` and change the one that starts with _”Unicorn vegan ...“_):

![Screen Shot 2019-09-16 at 9 52 09 AM](https://user-images.githubusercontent.com/492229/64963768-ca5f8700-d867-11e9-965e-b5a83633cebb.png)

2. Once you are done, add a description of the changes

![Screen Shot 2019-09-16 at 9 54 15 AM](https://user-images.githubusercontent.com/492229/64963916-0397f700-d868-11e9-886a-cb1b24e1606b.png)

3. Press "Commit changes"

![Screen Shot 2019-09-16 at 9 55 24 AM](https://user-images.githubusercontent.com/492229/64964000-304c0e80-d868-11e9-9de1-61c725f60364.png)

**Comment by SessionsHugues** [comment]
Ok, thanks for the tutorial Gab!
