### ISSUE TITLE
Fix page malfunctioning 

### ISSUE THREAD

**Issue by vigliensoni** [sessions-marteau/sessions-marteau-2.github.io#16]
The last two commits broke some code logic and there are spurious elements in the page

<img width="574" alt="Screen Shot 2019-11-28 at 10 22 21 AM" src="https://user-images.githubusercontent.com/492229/69817624-02206e80-11c9-11ea-9857-af165e94185d.png">

@splouf , I will revert these last two commits. The display of social media icons such as twitter and pinterest is handled by conditions that check if there is information in the config.yaml file. That is, when/if we have them, they will show up in the page.

I don't know if this error is related to the certificate of the page but, for whatever reason, the page now is not being served over https.

**Comment by vigliensoni** [comment]
This is what is being reported for the certificate:

<img width="765" alt="Screen Shot 2019-11-28 at 10 35 10 AM" src="https://user-images.githubusercontent.com/492229/69818462-cbe3ee80-11ca-11ea-8f1c-7b0db94d9649.png">

**Comment by vigliensoni** [comment]
So, I reverted those two commits (44e51f7ff15eba84e41066fb189f73543965da2f), the site now builds properly and the certificate works. 

@splouf was there something specific that you wanted to do in those commits?

Not sure yet about the extra elements rendered ...

**Comment by vigliensoni** [comment]
Fix in 709a7f727230160795064f738ba79738234b696f

**Comment by splouf** [comment]
thanks, I did something wrong sorry!

**Comment by vigliensoni** [comment]
No problem, I haven't had time before to work on this.

I also realized what you were trying to achieve: to get rid of the social links in the event, which is post. That is fixed now. 

We will need to put the program on the site. I saw that now is about 20 pieces long. Is this the final version?

**Comment by splouf** [comment]
just sent the program please wait a t very last minute to post the final program. It is better to have the surprise at the door no?
