### ISSUE TITLE
Upload podcast Shalabi

### ISSUE THREAD

**Issue by vigliensoni** [sessions-marteau/sessions-marteau-2.github.io#19]

**Comment by vigliensoni** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Upload Podcast 3](https://trello.com/c/3Yi9rA55/1-upload-podcast-3)

**Comment by vigliensoni** [comment]
File is now on Github. Missing to create the RSS feed and create the link in the digital distributors.

**Comment by vigliensoni** [comment]
- [ ] Create RSS
- [ ] Write description
- [ ] Proofread description
- [ ] Upload to iono.fm
- [ ] Upload to Spotify
- [ ] Upload to Apple

**Comment by vigliensoni** [comment]
@splouf 

Since the last podcast was so long (it weighted more than 200MB) I had to activate Git LFS and all *.mp3 are now managed with this different file system. 

It is possible that the streaming services did not like this technology for serving the podcast, and so we may need to find a different alternative. Let's wait a bit more and see what happens tomorrow.

**Comment by splouf** [comment]
ok lets see, otherwise split in 2 parts?

**Comment by vigliensoni** [comment]
Let's wait until tomorrow to see if the RSS syndication is fine as it is. Otherwise, we are going to try a different strategy.

**Comment by vigliensoni** [comment]
@splouf 

This is the current state:

- Session 1 and 2 podcasts are stored on Github using LFS
- Session 3 podcast is stored using a different provider

Results:

Sessions 1 and 2 are not reachable but session 3 is available. 

Outcome: 

- [ ] Move all podcast to a different hosting
- [ ] Change the RSS feed
- [ ] Eventually, Sessions Marteau should have it's own hosting space.

**Comment by splouf** [comment]
I do not know what are the consequences of one another. Maybe the simplest way and the most efficient way for the future?

**Comment by splouf** [comment]
it seems that it is only on Spotify the problem. Apple podcast show them all...

**Comment by vigliensoni** [comment]
Spotify is not the problem, is our free hosting solution on Github.

I have a solution (Shalabi's session is being hosted elsewhere)

I will work on this in the afternoon.

**Comment by splouf** [comment]
ok thanks

**Comment by vigliensoni** [comment]
- [ ] Waiting for RSS feed propagation

**Comment by splouf** [comment]
It seems to work on Spotify for all sessions but not on Apple Podcast. Only the Shalabi works.

**Comment by vigliensoni** [comment]
The podcast is now available on the platforms we are focusing (iTunes, Spotify, and iono)

I am closing this issue.
