### ISSUE TITLE
Proofread description session Shalabi.

### ISSUE THREAD

**Issue by vigliensoni** [sessions-marteau/sessions-marteau-2.github.io#22]
@splouf or @SessionsHugues 

Could you please proofread the description for the 3rd listening session podcast so that I can upload it to the streaming services?

These are the lines of code:

https://github.com/sessions-marteau/sessions-marteau-2.github.io/blob/0a19e209f283f21614c246f211a268597a3658fd/sessions-marteau.rss#L81-L91

**Comment by splouf** [comment]
We can maybe simplify to:
Sous le thème de "la musique psychédélique avant la psychedelia", il s’agit de la musique qui émerge à partir de la conscience et qui a influencé la musique psychédélique.

**Comment by vigliensoni** [comment]
No "Sam Shalabi presentera ..."?

**Comment by splouf** [comment]
his name is already in the title? On my phone I see only 7 words as the preview we can maybe add at the end as a second phrase: "Présenté par Sam Shalabi compositeur et improvisateur canado-égyptien."

Sous le thème de "la musique psychédélique avant la psychedelia", il s’agit de la musique qui émerge à partir de la conscience et qui a influencé la musique psychédélique. Présenté par Sam Shalabi compositeur et improvisateur canado-égyptien.

**Comment by vigliensoni** [comment]
Thank you.
