### ISSUE TITLE
Add text image to evenement-a-venir/

### ISSUE THREAD

**Issue by splouf** [sessions-marteau/sessions-marteau-2.github.io#25]
Can you please add this image to https://sessionsmarteau.com/evenement-a-venir/
![texte suivez-nous](https://user-images.githubusercontent.com/51759201/71011352-4366b880-20bb-11ea-99ef-b87c3e1dbd39.jpg)

**Comment by vigliensoni** [comment]
@splouf Is this fine with you?

**Comment by splouf** [comment]
that can work or this one with a pop-up for mailing list? I can program it from Mailchimp but not for one specific page...
![_DSC4099](https://user-images.githubusercontent.com/51759201/71014954-c6d6d880-20c0-11ea-835e-ebf52229cbb1.JPG)

**Comment by vigliensoni** [comment]
What do you mean? Having this image? Great! Actually, could you please upload a selection of low-res images of the third session to: ```uploads/session-003/pictures/```? Once the images are there, we can add them to the third session and update some of the other ones.

I don't really understand the pop-up for mailing list.

**Comment by splouf** [comment]
I did upload images for the session 3. It is not necessary to have a pop-up, it is just because there is nothing on the événement à venir page so it might bring more people to sing up.
