### ISSUE TITLE
Investigate how to embed Twitch stream on site

### ISSUE THREAD

**Issue by vigliensoni** [sessions-marteau/sessions-marteau-2.github.io#29]
https://dev.twitch.tv/docs/embed/video-and-clips

**Comment by vigliensoni** [comment]
So, @splouf , this is actually working, check

https://sessionsmarteau.com/streaming-test/

**Comment by splouf** [comment]
@vigliensoni this is great! But I don't know if ppl will open an account for adding their comments and questions. Maybe we can remove the twitch comments section and add instead a link for comments and questions like Facebook messaging or just our email?
