### ISSUE TITLE
Some YouTube playlists are not shareable

### ISSUE THREAD

**Issue by vigliensoni** [sessions-marteau/sessions-marteau-2.github.io#6]
It seems that only some YouTube playlists are embeddable in other sites. From https://support.google.com/youtube/answer/57793?co=GENIE.Platform%3DDesktop&hl=en:

Note: If videos aren’t appearing in an embedded playlist, some of the videos in the playlist may have had their embed option disabled by the uploader. Private videos will also not play in the playlist unless they've been shared with you by the uploader.

For Creators: You may want to ensure that the content you've included in your playlist contains only public videos that have the embed option enabled.

Also, see:

<img width="1087" alt="Screen Shot 2019-09-12 at 5 28 23 PM" src="https://user-images.githubusercontent.com/492229/64822419-eff84200-d582-11e9-8c82-16f02e50f5b8.png">

@splouf Shall we only link our YouTube channel?

**Comment by splouf** [comment]
I added embeded to my playlist but it seems that we need to work on the playlists to finish them because most of Cinema sous les étoiles playlists are not.
